export const PRODUCT_ACTION_TYPES = {
    GET_SHOP_PRODUCTS: 'GET_SHOP_PRODUCTS',
    CHOOSE_PRODUCT: 'CHOOSE_PRODUCT',
    RESET_ALERT: 'RESET_ALERT',
    GET_USER_PURCHASED: 'GET_USER_PURCHASED'
};
